services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native protocol

    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./clickhouse/prometheus.xml:/etc/clickhouse-server/config.d/prometheus.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dw-net

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - dw-net

  clickhouse-exporter:
    image: f1yegor/clickhouse-exporter
    container_name: clickhouse-exporter
    command: -scrape_uri=http://clickhouse:8123/
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - dw-net

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - dw-net

volumes:
  clickhouse_data:
  grafana_data:
  prometheus_data:

networks:
  dw-net:
    driver: bridge
