nyc_taxi_warehouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: 8123
      schema: analytics
      user: default
      password: ""
      secure: false
      verify: false
